### PR TITLE
Show skipped steps as ignored

### PR DESCRIPTION
**Pull request by kevinkuszyk**
This PR is the first part towards #4.  I've started with showing the skipped steps as ignored.

As you can see from the commits, there are a few things included in this PR:

1. Adding a `package-lock.json`.
2. Adding an npm run script to run the mockup feature.
3. Update to cucumber 3 as discussed
4. And finally, showing the skipped steps as ignored in team city.

In addition to the tests passing, I've tried it out on our team city server here, and all seems ok:

image

If you're happy with the direction, can you go ahead and merge? I'll send another PR next week for the option to only show scenarios in the team city output.

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
It looks like the build failed due to the `pending` Unicode escaping test.  I think cucumber must have tighten up on `pending` tests and made them fail the build.

If it's ok with you I can switch that test over to be `skipped` (i.e ignored), and the build should go green?

**Comment by oledid** [comment]
@kevinkuszyk Sure, pending tests can be skipped.

**Comment by kevinkuszyk** [comment]
Ok.  That that test is skipped now and the build is green.

**Comment by oledid** [comment]
Thanks.

I just sent a request to Jetbrains about building my teamcity-related repositories on their public teamcity-server. I will await their response before finishing the issue.

**Comment by oledid** [comment]
https://teamcity.jetbrains.com/project.html?projectId=TeamCityThirdPartyPlugins_CucumberJsonToTeamcity&tab=projectOverview

**Pull request merged**
